name: qmessentials
services:
  auth:
    build:
      context: ../auth
      dockerfile: Dockerfile.authservice
    environment:
      - PORT=3010
      - MONGODB_HOST=auth-db
      - MONGODB_PORT=27017
      - MONGODB_DATABASE_NAME=auth
      - DEFAULT_ADMIN_USER=admin
      - INITIAL_ADMIN_PASSWORD=changeMeNow!!!
      - JWT_SECRET=notVerySecret!!!
      - CORS_ALLOWED_ORIGIN=http://localhost:3000
    ports:
      - "3010:3010"
  auth-db:
    image: mongo:latest
    volumes:
      - "auth-db-volume:/data/db"
    ports:
      - "27017:27017"
  auth-reverse-proxy:
    build:
      context: ../auth
      dockerfile: Dockerfile.reverseproxy
    ports:
      - 8010:8010
    restart: always
  config-db:
    image: postgres
    environment: 
     - POSTGRES_USER=qmeconfig
     - POSTGRES_PASSWORD=n0t$3cr3t!
    ports: 
     - "5432:5432"
    volumes:
     - config-db-volume:/var/lib/postgresql/data
  config:
    build:
      context: ../config
      dockerfile: Dockerfile.configservice
    environment: 
      - USER=config
      - PORT=3020   
      - PGUSER=config
      - PGPASSWORD=n0tS3cr3t!
      - PGDATABASE=config
      - PGHOST=config-db
      - PGPORT=5410
    ports:
     - "3020:3020"
  client:
    build: ../qme-client
    environment:
      - BASE_URL=http://localhost:3000
      - AUTH_ENDPOINT=http://auth-reverse-proxy:8010
      - IRON_SESSION_PASSWORD=K5BLWMhisP1GMajAHH1WJQpBhsRoQmik
      - REDIS_URL=redis://client-cache:6379
    ports:
      - "3000:3000"
  client-cache:
    image: 'redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"

volumes:
  auth-db-volume:
  config-db-volume:

